### ISSUE TITLE
Decompiler error when loading level

### ISSUE THREAD

**Issue by sodifu** [RenolY2/battalion-level-editor#27]
I get a decompiler error when I try to load the BW1 SiegeOfVladstag.xml

> Exception in thread "main" java.lang.IllegalStateException
        at unluac.decompile.ControlFlowHandler.find_if_break(ControlFlowHandler.java:1144)
        at unluac.decompile.ControlFlowHandler.process(ControlFlowHandler.java:125)
        at unluac.decompile.Decompiler.decompile(Decompiler.java:136)
        at unluac.decompile.expression.ClosureExpression.printMain(ClosureExpression.java:103)
        at unluac.decompile.expression.ClosureExpression.printClosure(ClosureExpression.java:79)
        at unluac.decompile.statement.Assignment.print(Assignment.java:260)
        at unluac.decompile.statement.Statement.printTail(Statement.java:38)
        at unluac.decompile.statement.Statement.printSequence(Statement.java:25)
        at unluac.decompile.block.OuterBlock.print(OuterBlock.java:49)
        at unluac.decompile.Decompiler.print(Decompiler.java:161)
        at unluac.Main.main(Main.java:100)
activation status change <__main__.LevelEditor object at 0x0000029C7F6577F0> False

![image](https://github.com/user-attachments/assets/0655cab6-2257-4f95-970c-e96154193d18)

**Comment by RenolY2** [comment]
Does this version of the editor fix the decompiler issue?
https://github.com/RenolY2/battalion-level-editor/releases/tag/v1.2

**Comment by RenolY2** [comment]
I am closing this issue since I believe it shouldn't happen with newer versions of the editor anymore.
If the issue happens again you can file a new issue (make sure you are using the newest editor version though)
